### ISSUE TITLE
Binary exits silently in Docker container when connecting to database

### ISSUE THREAD

**Issue by affanshahid** [prisma/mobc#10]
https://github.com/Brendonovich/prisma-client-rust/issues/198 

Cross posting here as well since the last log is from mobc. Essentially when running inside a Docker container, the binary just exits silently (no panics, no errors) after emitting the following logs:

```
api_1             | 2022-11-04T14:36:55.157393Z TRACE query_core::executor::loader: Loading Postgres query connector...
api_1             | 2022-11-04T14:36:55.157654Z  INFO quaint::pooled: Starting a postgresql pool with 9 connections.
api_1             | 2022-11-04T14:36:55.157764Z TRACE query_core::executor::loader: Loaded Postgres query connector.
api_1             | 2022-11-04T14:36:55.170918Z DEBUG mobc: creating new connection from manager
```

More details on the original ticket.

**Comment by janpio** [comment]
Closing as we will archive this repo.
If this still is a thing, please report it in prisma/prisma. Thanks!
